[build]
builder = "nixpacks"

[deploy]
startCommand = "python simple_railway_demo.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.variables]
PYTHON_VERSION = "3.12"
PORT = "8000"